[build-system]
requires = ["hatchling", "uv-dynamic-versioning"]
build-backend = "hatchling.build"

[project]
name = "curious-pyapi"
dynamic = ["version"]
description = "Python interface for Curious API."
readme = "README.md"
authors = [
    { name = "Jon Cluce", email = "jon.clucas@childmind.org" }
]
requires-python = ">=3.14"
dependencies = [
    "fastexcel>=0.21.0",
    "httpx>=0.28.1",
    "polars>=1.44.0",
    "pydantic[email]>=2.13.4",
]
license-files = ["LICENSE"]
license = "MIT"
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.14",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Typing :: Typed",
]

[project.urls]
Repository = "https://github.com/childmindresearch/curious-pyapi"
Issues = "https://github.com/childmindresearch/curious-pyapi/issues"
Changelog = "https://github.com/childmindresearch/curious-pyapi/blob/main/CHANGELOG.md"

[tool.hatch.version]
source = "uv-dynamic-versioning"

[tool.pyright]
reportUnknownMemberType = false

[tool.ruff]
line-length = 88
target-version = "py314"

[tool.ruff.lint]
extend-select = ["A", "B904", "C4", "D", "E", "EM", "F541", "G", "I", "ICN", "LOG007", "N", "NPY", "PL", "RET", "RSE", "RUF", "Q", "T20", "TRY002", "TRY201", "TRY400", "TRY401", "UP032", "W"]
ignore = ["D203", "D212", "RUF002", "RUF003"]

[tool.ruff.lint.isort]
combine-as-imports = true
force-sort-within-sections = true
order-by-type = false
